[package]
name = "mandelbrot-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0"
image="0.14.0"
num_cpus = "1.0"
crossbeam="0.8"
rayon="1"
